# Numpy Matrix


In [2]:
import numpy as np

In [4]:
a=[1,4,7,2,9]
t=np.array(a)

In [6]:
t

array([1, 4, 7, 2, 9])

In [13]:
three=([1,2,3],[6,7,8],[11,12,15])
print(np.array(three))

[[ 1  2  3]
 [ 6  7  8]
 [11 12 15]]


In [16]:
np.arange(1,14,2)  #thired argument is step size   #1d array cuz single bracket

array([ 1,  3,  5,  7,  9, 11, 13])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((2,3))  #pass in a tuple  #2d array cuz 2brackets

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(0,100,20) #20 equal distace points between 0 and 100      #1d array cuz single bracket

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [26]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.rand(4)   #random values between 0 and 1

array([0.3012158 , 0.30033804, 0.76577083, 0.84932953])

In [28]:
np.random.randn(6) #patani konsi random values deta hai

array([ 0.94852368,  0.99929914,  1.45690754, -0.91265879, -0.69987775,
       -0.75524209])

In [31]:
np.random.randint(3,60,7) #thired argument is number of random values required between 3 and 60

array([44, 50, 46, 39, 36,  3, 37])

In [33]:
arr1=np.random.randint(10,50,10)
arr1

array([15, 14, 19, 29, 13, 10, 29, 39, 28, 33])

In [35]:
arr1.reshape(2,5) #size must be equal

array([[15, 14, 19, 29, 13],
       [10, 29, 39, 28, 33]])

In [38]:
arr1.max()

39

In [39]:
arr1.argmax() #position of max value

7

In [41]:
arr1.shape

(10,)

In [44]:
arr1=arr1.reshape(5,2)
arr1

array([[15, 14],
       [19, 29],
       [13, 10],
       [29, 39],
       [28, 33]])

In [45]:
arr1.shape

(5, 2)

In [47]:
arr1.dtype

dtype('int32')

# Indexing and Selection

In [62]:
import numpy as np

In [50]:
arrs=np.arange(1,12)
arrs

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
arrs[:6]

array([1, 2, 3, 4, 5, 6])

In [53]:
arrs[:7]=100   #in numpy array we can broadcast 
arrs

array([100, 100, 100, 100, 100, 100, 100,   8,   9,  10,  11])

In [63]:
arrs        #change has occured in orginal array also

array([100, 100, 100, 100, 100, 100, 100,   8,   9,  10,  11])

In [76]:
sarr_2d= np.array([[1,2,3],[5,6,7],[11,12,13]])
sarr_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 12, 13]])

NOTE: indexing of matrix start from 0 so first row and column will be 0 and 0

In [83]:
sarr_2d[2][0]   #double bracket notation for grabbing the element

11

In [85]:
sarr_2d[2,0]    #single bracket notation

11

In [89]:
sarr_2d[1:,1:]   #grab a section of the matrix

array([[ 6,  7],
       [12, 13]])

In [92]:
arrr=np.arange(1,13)
arrr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
bool1=arrr>6
bool1

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [100]:
arrr[bool1] #only true printed

array([ 7,  8,  9, 10, 11, 12])

In [102]:
arrr[arrr>9]

array([10, 11, 12])

## Numpy Operations

In [104]:
arr7=np.arange(0,12)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
arr7*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [109]:
arr7/2 #warning shown for 0/0

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [111]:
 arr7/0 #one more example

C:\Users\Puneet Sood\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Puneet Sood\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [113]:
np.sin(arr7)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [114]:
np.log(arr7)

C:\Users\Puneet Sood\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])